// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1oxt48PaeKy1d1EDHTFXo5INJlKZYbM',
    appId: '1:374041201622:web:353a8d23c94b4806067277',
    messagingSenderId: '374041201622',
    projectId: 'smartcivic-996df',
    authDomain: 'smartcivic-996df.firebaseapp.com',
    storageBucket: 'smartcivic-996df.appspot.com',
    measurementId: 'G-2VPC21J7X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHtWaxo1jrItiH5iPdhpM6uDYs1yMkgs',
    appId: '1:374041201622:android:6507730407872eff067277',
    messagingSenderId: '374041201622',
    projectId: 'smartcivic-996df',
    storageBucket: 'smartcivic-996df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Ln1lpdOL8rALzOzIvpZ3kh31vRiCyr0',
    appId: '1:374041201622:ios:b715938d34d7f03a067277',
    messagingSenderId: '374041201622',
    projectId: 'smartcivic-996df',
    storageBucket: 'smartcivic-996df.appspot.com',
    iosBundleId: 'com.example.citizenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Ln1lpdOL8rALzOzIvpZ3kh31vRiCyr0',
    appId: '1:374041201622:ios:b715938d34d7f03a067277',
    messagingSenderId: '374041201622',
    projectId: 'smartcivic-996df',
    storageBucket: 'smartcivic-996df.appspot.com',
    iosBundleId: 'com.example.citizenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1oxt48PaeKy1d1EDHTFXo5INJlKZYbM',
    appId: '1:374041201622:web:5bae1b1404035c9b067277',
    messagingSenderId: '374041201622',
    projectId: 'smartcivic-996df',
    authDomain: 'smartcivic-996df.firebaseapp.com',
    storageBucket: 'smartcivic-996df.firebasestorage.app',
    measurementId: 'G-MXVTSL85S1',
  );
}
