import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  Locale _currentLocale = const Locale('en');
  
  Locale get currentLocale => _currentLocale;
  String get currentLanguageCode => _currentLocale.languageCode;

  LanguageService() {
    _loadLocale();
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Smart Civic Mumbai',
      'welcome_back': 'Welcome Back!',
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'sign_in_desc': 'Sign in to report & track civic issues',
      'login': 'Login',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'new_citizen': 'New Citizen? Register here →',
      'mumbai_today': 'Mumbai Today',
      'quick_actions': 'Quick Actions',
      'mumbai_services': 'Mumbai Services',
      'report_issue': 'Report Issue',
      'file_complaint': 'File a complaint',
      'track_complaint': 'Track Complaint',
      'check_status': 'Check status',
      'hotspot_map': 'Hotspot Map',
      'view_areas': 'View issue areas',
      'my_issues': 'My Issues',
      'all_complaints': 'All your complaints',
      'helplines': 'Helplines & Contacts',
      'recent_activity': 'Recent Activity',
      'view_all': 'View all',
      'ward': 'Ward',
      'open': 'Open',
      'resolved': 'Resolved',
      'assigned': 'Forwarded',
      'in_progress': 'In Progress',
      'rejected': 'Rejected',
      'all': 'All',
      'sign_out': 'Sign out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'report_new_issue': 'Report New Issue',
      'issue_category': 'Issue Category',
      'issue_details': 'Issue Details',
      'title_hint': 'Problem title (e.g. Potholes in lane 4)',
      'desc_hint': 'Provide more details about the issue...',
      'voice_msg': 'Voice Message (Optional)',
      'photo_evidence': 'Photo Evidence',
      'location_ward': 'Location & Ward',
      'manual_address': 'Enter Manual Address / Nearby Landmark (Optional)',
      'ward_confirm': 'Confirm/Edit Ward Number (1-227)',
      'location': 'Location',
      'getting_location': 'Getting location...',
      'submit_report': 'Submit Report',
      'uploading': 'Uploading...',
      'success_msg': 'Report submitted successfully!',
      'error_title_req': 'Please enter a title',
      'error_desc_req': 'Please add a description',
      'error_ward_req': 'Ward is required',
      'error_ward_invalid': 'Enter valid ward (1-227)',
      'track_desc': 'Monitor the status of your reported civic issues in real-time.',
      'track_id': 'Track ID',
      'track_id_hint': 'e.g. BMC20250319143022',
      'error_no_issue': 'No issue found with Track ID:',
      'error_try_again': 'Something went wrong. Please try again.',
      'complaint_details': 'Complaint Details',
      'reported_by': 'Reported By',
      'filed_on': 'Filed On',
      'status_timeline': 'Status Timeline',
      'submitted': 'Submitted',
      'my_complaints': 'My Complaints',
      'no_complaints': 'No complaints filed yet',
      'tap_to_report': 'Tap the button below to report a civic issue',
      'retry': 'Retry',
      'sending_to_bmc': 'Sending to BMC...',
      'submit_complaint': 'Submit Complaint',
      'recording': 'Recording...',
      'voice_recorded': 'Voice Message Recorded',
      'tap_to_record': 'Tap to record voice message',
      'preview_hint': 'You can preview it before submitting',
      'submitted_title': 'Submitted!',
      'copy_id': 'Copy Track ID',
      'copied': 'Copied to clipboard',
      'done': 'Done',
      'complaint_desc': 'Monitor the status in real-time.',
      'reported_issues_all': 'Monitor all reported issues.',
      'view_complaint_details': 'View your complaint details.',
      'infrastructure': 'Infrastructure',
      'environment': 'Environment',
      'transport': 'Transport',
      'civic': 'Civic',
      'safety': 'Safety',
      'news_coastal_road': 'Coastal Road Project Phase 2 Nears Completion',
      'news_trees': 'BMC Plants 10,000 Trees Across Mumbai',
      'news_metro': 'Metro Line 3 Ridership Crosses 1 Lakh Daily',
      'news_dustbins': 'Smart Dustbins Installed in All 24 Wards',
      'news_cctv': '500 New CCTV Cameras Live in Western Suburbs',
      'check_inbox_desc': 'Please check your inbox and click the verification link.',
      'email_not_verified': 'Email Not Verified',
      'resend_email': 'Resend Email',
      'reset_password': 'Reset Password',
      'reset_desc': "We'll send a reset link to your email.",
      'send_link': 'Send Link',
      'smart_civic_system': 'Official BMC Smart Civic System',
      'ward_reporting': 'Reporting for Ward',
      'choose_photo': 'Choose Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'add_photo_evidence': 'Add clear photo of the issue',
      'change_photo': 'Change Photo',
      'location_details': 'Location Details',
      'capture_gps': 'Capture GPS to pin context',
      'location_captured': 'Location Captured',
      'redo': 'Redo',
      'locate': 'Locate',
      'bmc_footer': 'बृहन्मुंबई महानगरपालिका  •  BMC  •  © 2025',
      'news_coastal_desc': 'The 10.58 km stretch connecting Marine Lines to Worli set to open by mid-year.',
      'news_trees_desc': 'Green Mumbai Drive achieves record plantation in Aarey, Sanjay Gandhi Park zones.',
      'news_metro_desc': 'Aqua Line underground metro sees massive adoption since full launch.',
      'news_dustbins_desc': 'IoT-enabled waste bins now alert BMC crews when full.',
      'news_cctv_desc': 'Andheri, Borivali and Kandivali covered under Safe City expansion project.',
      'login_btn': 'Login',
      'signing_in': 'Signing in...',
      'login_subtitle': 'Sign in to report & track civic issues',
      'forgot_pass': 'Forgot Password?',
      'wards': 'Wards',
      'email_address': 'Email Address',
      'register_here': 'Register here →',
      'mumbai_news': 'Mumbai News',
      'avg_response': 'Avg\nResponse',
      'issues_resolved': 'Issues\nResolved',
      'registration_title': 'Citizen Registration',
      'create_account': 'Create your account',
      'fill_details': 'Fill in your details to get started',
      'full_name': 'Full Name',
      'mobile_number': 'Mobile Number',
      'ward_number': 'Ward Number',
      'creating_account': 'Creating account...',
      'register_btn': 'Register',
      'already_registered': 'Already registered? ',
      'account_created': 'Account Created!',
      'account_success_msg': 'Your account has been successfully created.',
      'verification_sent_to': 'A verification email has been sent to:',
      'verify_before_login': 'Please verify your email before logging in.',
      'setup_mpin_desc': 'Next: Set up your 4-digit MPIN for faster logins.',
      'setup_mpin_btn': 'Set MPIN →',
      'error_name_req': 'Full name is required',
      'error_phone_req': 'Mobile number is required',
      'error_phone_invalid': 'Enter a valid 10-digit number',
      'error_email_req': 'Email is required',
      'error_pass_req': 'Password is required',
      'error_pass_match': 'Passwords do not match',
      'error_generic': 'Something went wrong. Please try again.',
      'track_subtitle': 'Monitor status in real-time.',
      'cat_road': 'Road Damage',
      'cat_light': 'Street Light',
      'cat_garbage': 'Garbage',
      'cat_water': 'Water Leakage',
      'cat_traffic': 'Traffic Signal',
      'cat_encroach': 'Encroachment',
      'cat_tree': 'Tree Fallen',
      'cat_other': 'Other Issue',
      'firestore_index_required': 'Firestore Index Required',
      'something_went_wrong': 'Something went wrong',
      'index_needed_desc': 'A Firestore composite index is needed.',
      'permission_denied': 'Permission Denied',
      'permission_denied_desc': 'Your Firestore security rules are blocking this request.',
      'no_issues_found': 'No issues found',
    },
    'hi': {
      'app_title': 'स्मार्ट सिविक मुंबई',
      'welcome_back': 'आपका स्वागत है!',
      'greeting_morning': 'शुभ प्रभात',
      'greeting_afternoon': 'शुभ दोपहर',
      'greeting_evening': 'शुभ संध्या',
      'sign_in_desc': 'समस्याओं की रिपोर्ट करने और ट्रैक करने के लिए लॉगिन करें',
      'login': 'लॉगिन करें',
      'email': 'ईमेल पता',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?',
      'new_citizen': 'नए नागरिक? यहाँ रजिस्टर करें →',
      'mumbai_today': 'मुंबई आज',
      'quick_actions': 'त्वरित कार्रवाई',
      'mumbai_services': 'मुंबई सेवाएँ',
      'report_issue': 'समस्या रिपोर्ट करें',
      'file_complaint': 'शिकायत दर्ज करें',
      'track_complaint': 'शिकायत ट्रैक करें',
      'check_status': 'स्थिति जांचें',
      'hotspot_map': 'हॉटस्पॉट मैप',
      'view_areas': 'समस्या वाले क्षेत्र देखें',
      'my_issues': 'मेरी शिकायतें',
      'all_complaints': 'आपकी सभी शिकायतें',
      'helplines': 'हेल्पलाइन और संपर्क',
      'recent_activity': 'हाल की गतिविधि',
      'view_all': 'सभी देखें',
      'ward': 'वार्ड',
      'open': 'खुला',
      'resolved': 'समाधान',
      'assigned': 'विभाग को भेजा गया',
      'in_progress': 'प्रगति पर',
      'rejected': 'अस्वीकृत',
      'all': 'सभी',
      'sign_out': 'साइन आउट',
      'sign_out_confirm': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'report_new_issue': 'नई समस्या की रिपोर्ट करें',
      'issue_category': 'समस्या की श्रेणी',
      'issue_details': 'समस्या का विवरण',
      'title_hint': 'समस्या का शीर्षक (जैसे: गली 4 में गड्ढ़े)',
      'desc_hint': 'समस्या के बारे में अधिक विवरण प्रदान करें...',
      'voice_msg': 'ध्वनी संदेश (वैकल्पिक)',
      'photo_evidence': 'फोटो प्रमाण',
      'location_ward': 'स्थान और वार्ड',
      'manual_address': 'मैनुअल पता / पास का लैंडमार्क दर्ज करें (वैकल्पिक)',
      'ward_confirm': 'वार्ड नंबर की पुष्टि/संपादन करें (1-227)',
      'location': 'स्थान',
      'getting_location': 'स्थान प्राप्त किया जा रहा है...',
      'submit_report': 'रिपोर्ट सबमिट करें',
      'uploading': 'अपलोड हो रहा है...',
      'success_msg': 'रिपोर्ट सफलतापूर्वक सबमिट की गई!',
      'error_title_req': 'कृपया एक शीर्षक दर्ज करें',
      'error_desc_req': 'कृपया विवरण जोड़ें',
      'error_ward_req': 'वार्ड आवश्यक है',
      'error_ward_invalid': 'वैध वार्ड दर्ज करें (1-227)',
      'track_desc': 'वास्तविक समय में अपनी रिपोर्ट की गई नागरिक समस्याओं की स्थिति की निगरानी करें।',
      'track_id': 'ट्रैक आईडी',
      'track_id_hint': 'जैसे: BMC20250319143022',
      'error_no_issue': 'इस ट्रैक आईडी के साथ कोई समस्या नहीं मिली:',
      'error_try_again': 'कुछ गलत हो गया। कृपया पुन: प्रयास करें।',
      'complaint_details': 'शिकायत विवरण',
      'reported_by': 'रिपोर्टर',
      'filed_on': 'दिनांक',
      'status_timeline': 'स्थिति समयरेखा',
      'submitted': 'सबमिट किया गया',
      'my_complaints': 'मेरी शिकायतें',
      'no_complaints': 'अभी तक कोई शिकायत दर्ज नहीं की गई है',
      'tap_to_report': 'नागरिक समस्या की रिपोर्ट करने के लिए नीचे दिए गए बटन पर टैप करें',
      'retry': 'पुनः प्रयास करें',
      'sending_to_bmc': 'बीएमसी को भेज रहा है...',
      'submit_complaint': 'शिकायत दर्ज करें',
      'recording': 'रिकॉर्डिंग हो रही है...',
      'voice_recorded': 'ध्वनि संदेश रिकॉर्ड किया गया',
      'tap_to_record': 'ध्वनि संदेश रिकॉर्ड करने के लिए टैप करें',
      'preview_hint': 'आप सबमिट करने से पहले इसे सुन सकते हैं',
      'submitted_title': 'सबमिट किया गया!',
      'copy_id': 'ट्रैक आईडी कॉपी करें',
      'copied': 'क्लिपबोर्ड पर कॉपी किया गया',
      'done': 'हो गया',
      'complaint_desc': 'वास्तविक समय में स्थिति की निगरानी करें।',
      'reported_issues_all': 'सभी रिपोर्ट की गई समस्याओं की निगरानी करें।',
      'view_complaint_details': 'अपनी शिकायत का विवरण देखें।',
      'infrastructure': 'बुनियादी ढांचा',
      'environment': 'पर्यावरण',
      'transport': 'परिवहन',
      'civic': 'नागरिक',
      'safety': 'सुरक्षा',
      'news_coastal_road': 'कोस्टल रोड प्रोजेक्ट चरण 2 पूरा होने के करीब',
      'news_trees': 'बीएमसी ने मुंबई में 10,000 पेड़ लगाए',
      'news_metro': 'मेट्रो लाइन 3 की सवारी दैनिक 1 लाख के पार',
      'news_dustbins': 'सभी 24 वार्डों में स्मार्ट डस्टबिन लगाए गए',
      'news_cctv': 'पश्चिमी उपनगरों में 500 नए सीसीटीवी कैमरे लाइव',
      'check_inbox_desc': 'कृपया अपना इनबॉक्स चेक करें और वेरिफिकेशन लिंक पर क्लिक करें।',
      'email_not_verified': 'इमेल वेरिफाइड नहीं है',
      'resend_email': 'ईमेल दोबारा भेजें',
      'reset_password': 'पासवर्ड रीसेट करें',
      'reset_desc': "हम आपके ईमेल पर एक रीसेट लिंक भेजेंगे।",
      'send_link': 'लिंक भेजें',
      'smart_civic_system': 'आधिकारिक बीएमसी स्मार्ट सिविक सिस्टम',
      'ward_reporting': 'वार्ड के लिए रिपोर्टिंग',
      'choose_photo': 'फोटो चुनें',
      'camera': 'कैमरा',
      'gallery': 'गैलरी',
      'add_photo_evidence': 'समस्या की स्पष्ट फोटो जोड़ें',
      'change_photo': 'फोटो बदलें',
      'location_details': 'स्थान विवरण',
      'capture_gps': 'संदर्भ के लिए जीपीएस कैप्चर करें',
      'location_captured': 'स्थान प्राप्त हुआ',
      'redo': 'दोबारा करें',
      'locate': 'स्थान खोजें',
      'bmc_footer': 'बृहन्मुंबई महानगरपालिका  •  BMC  •  © 2025',
      'news_coastal_desc': 'मरीन लाइन्स को वर्ली से जोड़ने वाला 10.58 किमी का हिस्सा मध्य वर्ष तक खुलने के लिए तैयार है।',
      'news_trees_desc': 'ग्रीन मुंबई ड्राइव ने आरे, संजय गांधी पार्क क्षेत्रों में रिकॉर्ड पौधारोपण किया।',
      'news_metro_desc': 'एक्वा लाइन अंडरग्राउंड मेट्रो को पूर्ण लॉन्च के बाद से बड़े पैमाने पर अपनाया गया है।',
      'news_dustbins_desc': 'IoT-सक्षम कचरा डिब्बे अब भर जाने पर बीएमसी क्रू को सचेत करते हैं।',
      'news_cctv_desc': 'सेफ सिटी विस्तार परियोजना के तहत अंधेरी, बोरीवली और कांदीवली को कवर किया गया।',
      'login_btn': 'लॉगिन',
      'signing_in': 'साइन-इन हो रहा है...',
      'login_subtitle': 'समस्याओं की रिपोर्ट करने और ट्रैक करने के लिए लॉगिन करें',
      'forgot_pass': 'पासवर्ड भूल गए?',
      'wards': 'वार्ड',
      'email_address': 'ईमेल पता',
      'register_here': 'यहाँ रजिस्टर करें →',
      'mumbai_news': 'मुंबई समाचार',
      'avg_response': 'औसत\nप्रतिक्रिया',
      'issues_resolved': 'समाधान की गई\nसमस्याएं',
      'registration_title': 'नागरिक पंजीकरण',
      'create_account': 'अपना खाता बनाएं',
      'fill_details': 'शुरू करने के लिए अपना विवरण भरें',
      'full_name': 'पूरा नाम',
      'mobile_number': 'मोबाइल नंबर',
      'ward_number': 'वार्ड नंबर',
      'creating_account': 'खाता बनाया जा रहा है...',
      'register_btn': 'पंजीकरण करें',
      'already_registered': 'पहले से पंजीकृत हैं? ',
      'account_created': 'खाता बन गया!',
      'account_success_msg': 'आपका खाता सफलतापूर्वक बना दिया गया है।',
      'verification_sent_to': 'एक वेरिफिकेशन ईमेल यहाँ भेजा गया है:',
      'verify_before_login': 'लॉगिन करने से पहले कृपया अपना ईमेल वेरिफाई करें।',
      'setup_mpin_desc': 'अगला: त्वरित लॉगिन के लिए अपना 4-अंकों का MPIN सेट करें।',
      'setup_mpin_btn': 'MPIN सेट करें →',
      'error_name_req': 'पूरा नाम आवश्यक है',
      'error_phone_req': 'मोबाइल नंबर आवश्यक है',
      'error_phone_invalid': 'एक वैध 10-अंकीय नंबर दर्ज करें',
      'error_email_req': 'ईमेल आवश्यक है',
      'error_pass_req': 'पासवर्ड आवश्यक है',
      'error_pass_match': 'पासवर्ड मेल नहीं खाते',
      'error_generic': 'कुछ गलत हो गया। कृपया पुन: प्रयास करें।',
      'track_subtitle': 'वास्तविक समय में निगरानी करें।',
      'cat_road': 'सड़क क्षति',
      'cat_light': 'स्ट्रीट लाइट',
      'cat_garbage': 'कचरा',
      'cat_water': 'पानी का रिसाव',
      'cat_traffic': 'ट्रैफिक सिग्नल',
      'cat_encroach': 'अतिक्रमण',
      'cat_tree': 'पेड़ गिरना',
      'cat_other': 'अन्य समस्या',
      'firestore_index_required': 'फायरस्टोर इंडेक्स आवश्यक है',
      'something_went_wrong': 'कुछ गलत हो गया',
      'index_needed_desc': 'एक फायरस्टोर कम्पोजिट इंडेक्स की आवश्यकता है।',
      'permission_denied': 'अनुमति अस्वीकृत',
      'permission_denied_desc': 'आपके फायरस्टोर सुरक्षा नियम इस अनुरोध को रोक रहे हैं।',
      'no_issues_found': 'कोई समस्या नहीं मिली',
    },
    'mr': {
      'app_title': 'स्मार्ट सिविक मुंबई',
      'welcome_back': 'तुमचे स्वागत आहे!',
      'greeting_morning': 'शुभ प्रभात',
      'greeting_afternoon': 'शुभ दुपार',
      'greeting_evening': 'शुभ संध्याकाळ',
      'sign_in_desc': 'समस्या नोंदवण्यासाठी आणि ट्रॅक करण्यासाठी लॉगिन करा',
      'login': 'लॉगिन करा',
      'email': 'ईमेल पत्ता',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड विसरलात?',
      'new_citizen': 'नवीन नागरिक? येथे नोंदणी करा →',
      'mumbai_today': 'मुंबई आज',
      'quick_actions': 'त्वरीत क्रिया',
      'mumbai_services': 'मुंबई सेवा',
      'report_issue': 'तक्रार नोंदवा',
      'file_complaint': 'तक्रार दाखल करा',
      'track_complaint': 'तक्रार ट्रॅक करा',
      'check_status': 'स्थिती तपासा',
      'hotspot_map': 'हॉटस्पॉट नकाशा',
      'view_areas': 'समस्या क्षेत्रे पहा',
      'my_issues': 'माझ्या तक्रारी',
      'all_complaints': 'तुमच्या सर्व तक्रारी',
      'helplines': 'हेल्पलाईन आणि संपर्क',
      'recent_activity': 'अलीकडील क्रियाकलाप',
      'view_all': 'सर्व पहा',
      'ward': 'वार्ड',
      'open': 'खुले',
      'resolved': 'निकाली',
      'assigned': 'विभागाकडे पाठवले',
      'in_progress': 'प्रगतीपथावर',
      'rejected': 'नाकारले',
      'all': 'सर्व',
      'sign_out': 'साइन आउट',
      'sign_out_confirm': 'तुमची खात्री आहे की तुम्ही साइन आउट करू इच्छिता?',
      'cancel': 'रद्द करा',
      'report_new_issue': 'नवीन तक्रार नोंदवा',
      'issue_category': 'समस्येचा प्रकार',
      'issue_details': 'तक्रारीचा तपशील',
      'title_hint': 'समस्येचे शीर्षक (उदा. गल्ली क्र. ४ मधील खड्डे)',
      'desc_hint': 'समस्येबद्दल अधिक माहिती द्या...',
      'voice_msg': 'ध्वनी संदेश (पर्यायी)',
      'photo_evidence': 'फोटो पुरावा',
      'location_ward': 'ठिकाण आणि वॉर्ड',
      'manual_address': 'मॅन्युअल पत्ता / जवळची खूण प्रविष्ट करा (पर्यायी)',
      'ward_confirm': 'वार्ड क्रमांक निश्चित/संपादन करा (१-२२७)',
      'location': 'ठिकाण',
      'getting_location': 'स्थान शोधत आहे...',
      'submit_report': 'तक्रार सादर करा',
      'uploading': 'अपलोड होत आहे...',
      'success_msg': 'तक्रार यशस्वीरित्या नोंदवली गेली!',
      'error_title_req': 'कृपया शीर्षक प्रविष्ट करा',
      'error_desc_req': 'कृपया माहिती जोडा',
      'error_ward_req': 'वार्ड आवश्यक आहे',
      'error_ward_invalid': 'वैध वॉर्ड प्रविष्ट करा (१-२२७)',
      'track_desc': 'तुमच्या नोंदवलेल्या नागरी समस्यांच्या स्थितीचे रिअल-टाइममध्ये निरीक्षण करा.',
      'track_id': 'ट्रॅक आयडी',
      'track_id_hint': 'उदा. BMC20250319143022',
      'error_no_issue': 'ह्या ट्रॅक आयडीसह कोणतीही तक्रार आढळली नाही:',
      'error_try_again': 'काहीतरी चुकले. कृपया पुन्हा प्रयत्न करा.',
      'complaint_details': 'तक्रार तपशील',
      'reported_by': 'तक्रारदार',
      'filed_on': 'दिनांक',
      'status_timeline': 'स्थिती कालमर्यादा',
      'submitted': 'सादर केले',
      'my_complaints': 'माझ्या तक्रारी',
      'no_complaints': 'अद्याप एकही तक्रार नोंदवलेली नाही',
      'tap_to_report': 'नागरी समस्या नोंदवण्यासाठी खालील बटणावर टॅप करा',
      'retry': 'पुन्हा प्रयत्न करा',
      'sending_to_bmc': 'बीएमसीकडे पाठवत आहे...',
      'submit_complaint': 'शिकायत सादर करा',
      'recording': 'रेकॉर्डिंग सुरू आहे...',
      'voice_recorded': 'ध्वनी संदेश रेकॉर्ड झाला',
      'tap_to_record': 'ध्वनी संदेश रेकॉर्ड करण्यासाठी टॅप करा',
      'preview_hint': 'तुम्ही सादर करण्यापूर्वी ते ऐकू शकता',
      'submitted_title': 'सादर केले!',
      'copy_id': 'ट्रॅक आयडी कॉपी करा',
      'copied': 'क्लिपबोर्डवर कॉपी झाले',
      'done': 'झाले',
      'complaint_desc': 'रिअल-टाइममध्ये स्थितीचे निरीक्षण करा.',
      'reported_issues_all': 'सर्व नोंदवलेल्या समस्यांचे निरीक्षण करा.',
      'view_complaint_details': 'तुमच्या तक्रारीचा तपशील पहा.',
      'infrastructure': 'पायाभूत सुविधा',
      'environment': 'पर्यावरण',
      'transport': 'परिवहन',
      'civic': 'नागरिक',
      'safety': 'सुरक्षा',
      'news_coastal_road': 'कोस्टल रोड प्रकल्प टप्पा २ पूर्णत्वाच्या जवळ',
      'news_trees': 'बीएमसीने मुंबईत १०,००० झाडे लावली',
      'news_metro': 'मेट्रो लाईन ३ प्रवासी संख्या दररोज १ लाखाच्या पुढे',
      'news_dustbins': 'सर्व २४ वॉर्डांमध्ये स्मार्ट डस्टबिन बसवले',
      'news_cctv': 'पश्चिम उपनगरात ५०० नवीन सीसीटीव्ही कॅमेरे सुरू',
      'check_inbox_desc': 'कृपया तुमचे इनबॉक्स तपासा आणि व्हेरिफिकेशन लिंकवर क्लिक करा।',
      'email_not_verified': 'ईमेल व्हेरिफाईड नाही',
      'resend_email': 'ईमेल पुन्हा पाठवा',
      'reset_password': 'पासवर्ड रीसेट करा',
      'reset_desc': "आम्ही तुमच्या ईमेलवर रीसेट लिंक पाठवू.",
      'send_link': 'लिंक पाठवा',
      'smart_civic_system': 'आधिकृत बीएमसी स्मार्ट सिविक सिस्टम',
      'ward_reporting': 'वॉर्डसाठी तक्रार नोंदवत आहे',
      'choose_photo': 'फोटो निवडा',
      'camera': 'कॅमेरा',
      'gallery': 'गॅलरी',
      'add_photo_evidence': 'समस्येचा स्पष्ट फोटो जोडा',
      'change_photo': 'फोटो बदला',
      'location_details': 'ठिकाण तपशील',
      'capture_gps': 'ठिकाण निश्चित करण्यासाठी जीपीएस वापरा',
      'location_captured': 'स्थान निश्चित झाले',
      'redo': 'पुन्हा करा',
      'locate': 'स्थान शोधा',
      'bmc_footer': 'बृहन्मुंबई महानगरपालिका  •  BMC  •  © २०२५',
      'news_coastal_desc': 'मरीन लाइन्सला वरळीशी जोडणारा १०.५८ किमीचा टप्पा वर्षाच्या मध्यापर्यंत सुरू होणार आहे.',
      'news_trees_desc': 'ग्रीन मुंबई मोहिमेने आरे, संजय गांधी पार्क क्षेत्रात विक्रमी वृक्षारोपण केले.',
      'news_metro_desc': 'एक्वा लाईन अंडरग्राउंड मेट्रोला पूर्ण लाँच झाल्यापासून मोठा प्रतिसाद मिळत आहे.',
      'news_dustbins_desc': 'IoT-सक्षम कचरा पेट्या आता भरल्यावर बीएमसी कर्मचाऱ्यांना अलर्ट पाठवतात.',
      'news_cctv_desc': 'सेफ सिटी विस्तार प्रकल्पांतर्गत अंधेरी, बोरीवली आणि कांदिवलीचा समावेश करण्यात आला.',
      'login_btn': 'लॉगिन करा',
      'signing_in': 'साइन-इन होत आहे...',
      'login_subtitle': 'समस्या नोंदवण्यासाठी आणि ट्रॅक करण्यासाठी लॉगिन करा',
      'forgot_pass': 'पासवर्ड विसरलात?',
      'wards': 'वॉर्ड',
      'email_address': 'ईमेल पत्ता',
      'register_here': 'येथे नोंदणी करा →',
      'mumbai_news': 'मुंबई बातम्या',
      'avg_response': 'सरासरी\nप्रतिसाद',
      'issues_resolved': 'निकाली काढलेल्या\nतक्रारी',
      'registration_title': 'नागरिक नोंदणी',
      'create_account': 'तुमचे खाते तयार करा',
      'fill_details': 'सुरू करण्यासाठी तुमची माहिती भरा',
      'full_name': 'पूर्ण नाव',
      'mobile_number': 'मोबाईल नंबर',
      'ward_number': 'वॉर्ड नंबर',
      'creating_account': 'खाते तयार होत आहे...',
      'register_btn': 'नोंदणी करा',
      'already_registered': 'आधीच नोंदणी केली आहे? ',
      'account_created': 'खाते तयार झाले!',
      'account_success_msg': 'तुमचे खाते यशस्वीरित्या तयार झाले आहे.',
      'verification_sent_to': 'एक व्हेरिफिकेशन ईमेल येथे पाठवला आहे:',
      'verify_before_login': 'लॉगिन करण्यापूर्वी कृपया तुमचा ईमेल व्हेरिफाईड करा.',
      'setup_mpin_desc': 'पुढील: जलद लॉगिनसाठी तुमचा 4-अंकी MPIN सेट करा.',
      'setup_mpin_btn': 'MPIN सेट करा →',
      'error_name_req': 'पूर्ण नाव आवश्यक आहे',
      'error_phone_req': 'मोबाईल नंबर आवश्यक आहे',
      'error_phone_invalid': 'एक वैध १०-अंकी नंबर प्रविष्ट करा',
      'error_email_req': 'ईमेल आवश्यक आहे',
      'error_pass_req': 'पासवर्ड आवश्यक आहे',
      'error_pass_match': 'पासवर्ड जुळत नाहीत',
      'error_generic': 'काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.',
      'track_subtitle': 'रिअल-टाइममध्ये निरीक्षण करा.',
      'cat_road': 'रस्ते खराब',
      'cat_light': 'स्ट्रीट लाईट',
      'cat_garbage': 'कचरा समस्या',
      'cat_water': 'पानी गळती',
      'cat_traffic': 'ट्रॅफिक सिग्नल',
      'cat_encroach': 'अतिक्रमण',
      'cat_tree': 'झाड पडणे',
      'cat_other': 'इतर समस्या',
      'firestore_index_required': 'फायरस्टोर इंडेक्स आवश्यक आहे',
      'something_went_wrong': 'कुछ गलत हो गया',
      'index_needed_desc': 'एक फायरस्टोर कम्पोजिट इंडेक्स की आवश्यकता है।',
      'permission_denied': 'अनुमति अस्वीकृत',
      'permission_denied_desc': 'आपके फायरस्टोर सुरक्षा नियम इस अनुरोध को रोक रहे हैं।',
      'no_issues_found': 'कोई समस्या नहीं मिली',
    }
  };

  String translate(String key) {
    return _translations[_currentLocale.languageCode]?[key] ?? key;
  }

  Future<void> setLocale(String languageCode) async {
    if (_currentLocale.languageCode == languageCode) return;
    _currentLocale = Locale(languageCode);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }

  Future<void> toggleLanguage() async {
    if (_currentLocale.languageCode == 'en') {
      await setLocale('hi');
    } else if (_currentLocale.languageCode == 'hi') {
      await setLocale('mr');
    } else {
      await setLocale('en');
    }
  }

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString('language_code') ?? 'en';
    _currentLocale = Locale(code);
    notifyListeners();
  }
}
